/*
 * Minha Pelada API
 * Servico para controle de grupos relacionados à pratica de esportes.  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: helderfalcaob@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EvaluationSummaryUnit;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * EvaluationSummary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-10-08T21:30:47.970-03:00")
public class EvaluationSummary {
  @SerializedName("averageEvaluationValue")
  private BigDecimal averageEvaluationValue = null;

  @SerializedName("averageSummaryEvaluationValue")
  private List<EvaluationSummaryUnit> averageSummaryEvaluationValue = null;

  @SerializedName("bestEvaluation")
  private EvaluationSummaryUnit bestEvaluation = null;

  @SerializedName("worstEvaluation")
  private EvaluationSummaryUnit worstEvaluation = null;

  public EvaluationSummary averageEvaluationValue(BigDecimal averageEvaluationValue) {
    this.averageEvaluationValue = averageEvaluationValue;
    return this;
  }

   /**
   * Get averageEvaluationValue
   * @return averageEvaluationValue
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getAverageEvaluationValue() {
    return averageEvaluationValue;
  }

  public void setAverageEvaluationValue(BigDecimal averageEvaluationValue) {
    this.averageEvaluationValue = averageEvaluationValue;
  }

  public EvaluationSummary averageSummaryEvaluationValue(List<EvaluationSummaryUnit> averageSummaryEvaluationValue) {
    this.averageSummaryEvaluationValue = averageSummaryEvaluationValue;
    return this;
  }

  public EvaluationSummary addAverageSummaryEvaluationValueItem(EvaluationSummaryUnit averageSummaryEvaluationValueItem) {
    if (this.averageSummaryEvaluationValue == null) {
      this.averageSummaryEvaluationValue = new ArrayList<EvaluationSummaryUnit>();
    }
    this.averageSummaryEvaluationValue.add(averageSummaryEvaluationValueItem);
    return this;
  }

   /**
   * Get averageSummaryEvaluationValue
   * @return averageSummaryEvaluationValue
  **/
  @ApiModelProperty(value = "")
  public List<EvaluationSummaryUnit> getAverageSummaryEvaluationValue() {
    return averageSummaryEvaluationValue;
  }

  public void setAverageSummaryEvaluationValue(List<EvaluationSummaryUnit> averageSummaryEvaluationValue) {
    this.averageSummaryEvaluationValue = averageSummaryEvaluationValue;
  }

  public EvaluationSummary bestEvaluation(EvaluationSummaryUnit bestEvaluation) {
    this.bestEvaluation = bestEvaluation;
    return this;
  }

   /**
   * Get bestEvaluation
   * @return bestEvaluation
  **/
  @ApiModelProperty(value = "")
  public EvaluationSummaryUnit getBestEvaluation() {
    return bestEvaluation;
  }

  public void setBestEvaluation(EvaluationSummaryUnit bestEvaluation) {
    this.bestEvaluation = bestEvaluation;
  }

  public EvaluationSummary worstEvaluation(EvaluationSummaryUnit worstEvaluation) {
    this.worstEvaluation = worstEvaluation;
    return this;
  }

   /**
   * Get worstEvaluation
   * @return worstEvaluation
  **/
  @ApiModelProperty(value = "")
  public EvaluationSummaryUnit getWorstEvaluation() {
    return worstEvaluation;
  }

  public void setWorstEvaluation(EvaluationSummaryUnit worstEvaluation) {
    this.worstEvaluation = worstEvaluation;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvaluationSummary evaluationSummary = (EvaluationSummary) o;
    return Objects.equals(this.averageEvaluationValue, evaluationSummary.averageEvaluationValue) &&
        Objects.equals(this.averageSummaryEvaluationValue, evaluationSummary.averageSummaryEvaluationValue) &&
        Objects.equals(this.bestEvaluation, evaluationSummary.bestEvaluation) &&
        Objects.equals(this.worstEvaluation, evaluationSummary.worstEvaluation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageEvaluationValue, averageSummaryEvaluationValue, bestEvaluation, worstEvaluation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvaluationSummary {\n");
    
    sb.append("    averageEvaluationValue: ").append(toIndentedString(averageEvaluationValue)).append("\n");
    sb.append("    averageSummaryEvaluationValue: ").append(toIndentedString(averageSummaryEvaluationValue)).append("\n");
    sb.append("    bestEvaluation: ").append(toIndentedString(bestEvaluation)).append("\n");
    sb.append("    worstEvaluation: ").append(toIndentedString(worstEvaluation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

