/*
 * Minha Pelada API
 * Servico para controle de grupos relacionados à pratica de esportes.  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: helderfalcaob@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Group
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-09-12T22:18:06.254-03:00")
public class Group {
  @SerializedName("_id")
  private String id = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("idIntegrantes")
  private List<String> idIntegrantes = null;

  @SerializedName("idPartidas")
  private List<String> idPartidas = null;

  @SerializedName("idPartidasPlanejadas")
  private List<String> idPartidasPlanejadas = null;

  @SerializedName("idGastos")
  private List<String> idGastos = null;

  /**
   * Status do grupo
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ATIVO("ativo"),
    
    INATIVO("inativo"),
    
    REMOVIDO("removido");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("idAdmin")
  private String idAdmin = null;

  public Group id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Group nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public Group idIntegrantes(List<String> idIntegrantes) {
    this.idIntegrantes = idIntegrantes;
    return this;
  }

  public Group addIdIntegrantesItem(String idIntegrantesItem) {
    if (this.idIntegrantes == null) {
      this.idIntegrantes = new ArrayList<String>();
    }
    this.idIntegrantes.add(idIntegrantesItem);
    return this;
  }

   /**
   * Get idIntegrantes
   * @return idIntegrantes
  **/
  @ApiModelProperty(value = "")
  public List<String> getIdIntegrantes() {
    return idIntegrantes;
  }

  public void setIdIntegrantes(List<String> idIntegrantes) {
    this.idIntegrantes = idIntegrantes;
  }

  public Group idPartidas(List<String> idPartidas) {
    this.idPartidas = idPartidas;
    return this;
  }

  public Group addIdPartidasItem(String idPartidasItem) {
    if (this.idPartidas == null) {
      this.idPartidas = new ArrayList<String>();
    }
    this.idPartidas.add(idPartidasItem);
    return this;
  }

   /**
   * Get idPartidas
   * @return idPartidas
  **/
  @ApiModelProperty(value = "")
  public List<String> getIdPartidas() {
    return idPartidas;
  }

  public void setIdPartidas(List<String> idPartidas) {
    this.idPartidas = idPartidas;
  }

  public Group idPartidasPlanejadas(List<String> idPartidasPlanejadas) {
    this.idPartidasPlanejadas = idPartidasPlanejadas;
    return this;
  }

  public Group addIdPartidasPlanejadasItem(String idPartidasPlanejadasItem) {
    if (this.idPartidasPlanejadas == null) {
      this.idPartidasPlanejadas = new ArrayList<String>();
    }
    this.idPartidasPlanejadas.add(idPartidasPlanejadasItem);
    return this;
  }

   /**
   * Get idPartidasPlanejadas
   * @return idPartidasPlanejadas
  **/
  @ApiModelProperty(value = "")
  public List<String> getIdPartidasPlanejadas() {
    return idPartidasPlanejadas;
  }

  public void setIdPartidasPlanejadas(List<String> idPartidasPlanejadas) {
    this.idPartidasPlanejadas = idPartidasPlanejadas;
  }

  public Group idGastos(List<String> idGastos) {
    this.idGastos = idGastos;
    return this;
  }

  public Group addIdGastosItem(String idGastosItem) {
    if (this.idGastos == null) {
      this.idGastos = new ArrayList<String>();
    }
    this.idGastos.add(idGastosItem);
    return this;
  }

   /**
   * Get idGastos
   * @return idGastos
  **/
  @ApiModelProperty(value = "")
  public List<String> getIdGastos() {
    return idGastos;
  }

  public void setIdGastos(List<String> idGastos) {
    this.idGastos = idGastos;
  }

  public Group status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Status do grupo
   * @return status
  **/
  @ApiModelProperty(value = "Status do grupo")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Group idAdmin(String idAdmin) {
    this.idAdmin = idAdmin;
    return this;
  }

   /**
   * Get idAdmin
   * @return idAdmin
  **/
  @ApiModelProperty(value = "")
  public String getIdAdmin() {
    return idAdmin;
  }

  public void setIdAdmin(String idAdmin) {
    this.idAdmin = idAdmin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Group group = (Group) o;
    return Objects.equals(this.id, group.id) &&
        Objects.equals(this.nome, group.nome) &&
        Objects.equals(this.idIntegrantes, group.idIntegrantes) &&
        Objects.equals(this.idPartidas, group.idPartidas) &&
        Objects.equals(this.idPartidasPlanejadas, group.idPartidasPlanejadas) &&
        Objects.equals(this.idGastos, group.idGastos) &&
        Objects.equals(this.status, group.status) &&
        Objects.equals(this.idAdmin, group.idAdmin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, nome, idIntegrantes, idPartidas, idPartidasPlanejadas, idGastos, status, idAdmin);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Group {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    idIntegrantes: ").append(toIndentedString(idIntegrantes)).append("\n");
    sb.append("    idPartidas: ").append(toIndentedString(idPartidas)).append("\n");
    sb.append("    idPartidasPlanejadas: ").append(toIndentedString(idPartidasPlanejadas)).append("\n");
    sb.append("    idGastos: ").append(toIndentedString(idGastos)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    idAdmin: ").append(toIndentedString(idAdmin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

