/*
 * Minha Pelada API
 * Servico para controle de grupos relacionados à pratica de esportes.  
 *
 * OpenAPI spec version: 1.0.0
 * Contact: helderfalcaob@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InlineResponse2005
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-10T14:44:58.749-02:00")
public class InlineResponse2005 {
  @SerializedName("id")
  private String id = null;

  @SerializedName("userName")
  private String userName = null;

  @SerializedName("tokenGoogle")
  private String tokenGoogle = null;

  @SerializedName("tokenFacebook")
  private String tokenFacebook = null;

  @SerializedName("nome")
  private String nome = null;

  @SerializedName("foto")
  private String foto = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("senha")
  private String senha = null;

  @SerializedName("telefone")
  private String telefone = null;

  @SerializedName("evaluated")
  private Boolean evaluated = null;

  @SerializedName("evaluatedValue")
  private BigDecimal evaluatedValue = null;

  @SerializedName("status")
  private String status = null;

  public InlineResponse2005 id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public InlineResponse2005 userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public InlineResponse2005 tokenGoogle(String tokenGoogle) {
    this.tokenGoogle = tokenGoogle;
    return this;
  }

   /**
   * Get tokenGoogle
   * @return tokenGoogle
  **/
  @ApiModelProperty(value = "")
  public String getTokenGoogle() {
    return tokenGoogle;
  }

  public void setTokenGoogle(String tokenGoogle) {
    this.tokenGoogle = tokenGoogle;
  }

  public InlineResponse2005 tokenFacebook(String tokenFacebook) {
    this.tokenFacebook = tokenFacebook;
    return this;
  }

   /**
   * Get tokenFacebook
   * @return tokenFacebook
  **/
  @ApiModelProperty(value = "")
  public String getTokenFacebook() {
    return tokenFacebook;
  }

  public void setTokenFacebook(String tokenFacebook) {
    this.tokenFacebook = tokenFacebook;
  }

  public InlineResponse2005 nome(String nome) {
    this.nome = nome;
    return this;
  }

   /**
   * Get nome
   * @return nome
  **/
  @ApiModelProperty(value = "")
  public String getNome() {
    return nome;
  }

  public void setNome(String nome) {
    this.nome = nome;
  }

  public InlineResponse2005 foto(String foto) {
    this.foto = foto;
    return this;
  }

   /**
   * Get foto
   * @return foto
  **/
  @ApiModelProperty(value = "")
  public String getFoto() {
    return foto;
  }

  public void setFoto(String foto) {
    this.foto = foto;
  }

  public InlineResponse2005 email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public InlineResponse2005 senha(String senha) {
    this.senha = senha;
    return this;
  }

   /**
   * Get senha
   * @return senha
  **/
  @ApiModelProperty(value = "")
  public String getSenha() {
    return senha;
  }

  public void setSenha(String senha) {
    this.senha = senha;
  }

  public InlineResponse2005 telefone(String telefone) {
    this.telefone = telefone;
    return this;
  }

   /**
   * Get telefone
   * @return telefone
  **/
  @ApiModelProperty(value = "")
  public String getTelefone() {
    return telefone;
  }

  public void setTelefone(String telefone) {
    this.telefone = telefone;
  }

  public InlineResponse2005 evaluated(Boolean evaluated) {
    this.evaluated = evaluated;
    return this;
  }

   /**
   * Get evaluated
   * @return evaluated
  **/
  @ApiModelProperty(value = "")
  public Boolean isEvaluated() {
    return evaluated;
  }

  public void setEvaluated(Boolean evaluated) {
    this.evaluated = evaluated;
  }

  public InlineResponse2005 evaluatedValue(BigDecimal evaluatedValue) {
    this.evaluatedValue = evaluatedValue;
    return this;
  }

   /**
   * Get evaluatedValue
   * @return evaluatedValue
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getEvaluatedValue() {
    return evaluatedValue;
  }

  public void setEvaluatedValue(BigDecimal evaluatedValue) {
    this.evaluatedValue = evaluatedValue;
  }

  public InlineResponse2005 status(String status) {
    this.status = status;
    return this;
  }

   /**
   * User Status
   * @return status
  **/
  @ApiModelProperty(value = "User Status")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2005 inlineResponse2005 = (InlineResponse2005) o;
    return Objects.equals(this.id, inlineResponse2005.id) &&
        Objects.equals(this.userName, inlineResponse2005.userName) &&
        Objects.equals(this.tokenGoogle, inlineResponse2005.tokenGoogle) &&
        Objects.equals(this.tokenFacebook, inlineResponse2005.tokenFacebook) &&
        Objects.equals(this.nome, inlineResponse2005.nome) &&
        Objects.equals(this.foto, inlineResponse2005.foto) &&
        Objects.equals(this.email, inlineResponse2005.email) &&
        Objects.equals(this.senha, inlineResponse2005.senha) &&
        Objects.equals(this.telefone, inlineResponse2005.telefone) &&
        Objects.equals(this.evaluated, inlineResponse2005.evaluated) &&
        Objects.equals(this.evaluatedValue, inlineResponse2005.evaluatedValue) &&
        Objects.equals(this.status, inlineResponse2005.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userName, tokenGoogle, tokenFacebook, nome, foto, email, senha, telefone, evaluated, evaluatedValue, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2005 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    tokenGoogle: ").append(toIndentedString(tokenGoogle)).append("\n");
    sb.append("    tokenFacebook: ").append(toIndentedString(tokenFacebook)).append("\n");
    sb.append("    nome: ").append(toIndentedString(nome)).append("\n");
    sb.append("    foto: ").append(toIndentedString(foto)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    senha: ").append(toIndentedString(senha)).append("\n");
    sb.append("    telefone: ").append(toIndentedString(telefone)).append("\n");
    sb.append("    evaluated: ").append(toIndentedString(evaluated)).append("\n");
    sb.append("    evaluatedValue: ").append(toIndentedString(evaluatedValue)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

