/*
 * Minha Pelada API
 * Servico para controle de grupos relacionados à pratica de esportes.  
 *
 * OpenAPI spec version: 1.5.7
 * Contact: helderfalcaob@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.User;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * Time
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-10T20:37:37.884-02:00")
public class Time {
  @SerializedName("players")
  private List<User> players = null;

  @SerializedName("timeValue")
  private BigDecimal timeValue = null;

  public Time players(List<User> players) {
    this.players = players;
    return this;
  }

  public Time addPlayersItem(User playersItem) {
    if (this.players == null) {
      this.players = new ArrayList<User>();
    }
    this.players.add(playersItem);
    return this;
  }

   /**
   * Get players
   * @return players
  **/
  @ApiModelProperty(value = "")
  public List<User> getPlayers() {
    return players;
  }

  public void setPlayers(List<User> players) {
    this.players = players;
  }

  public Time timeValue(BigDecimal timeValue) {
    this.timeValue = timeValue;
    return this;
  }

   /**
   * Get timeValue
   * @return timeValue
  **/
  @ApiModelProperty(value = "")
  public BigDecimal getTimeValue() {
    return timeValue;
  }

  public void setTimeValue(BigDecimal timeValue) {
    this.timeValue = timeValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Time time = (Time) o;
    return Objects.equals(this.players, time.players) &&
        Objects.equals(this.timeValue, time.timeValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(players, timeValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Time {\n");
    
    sb.append("    players: ").append(toIndentedString(players)).append("\n");
    sb.append("    timeValue: ").append(toIndentedString(timeValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

